steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/alx-portfolio-image-to-pdf/alx-portfolio-image-to-pdf",
        "./backend",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/${PROJECT_ID}/alx-portfolio-image-to-pdf/alx-portfolio-image-to-pdf",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "alx-portfolio-image-to-pdf",
        "--image",
        "gcr.io/${PROJECT_ID}/alx-portfolio-image-to-pdf/alx-portfolio-image-to-pdf",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/${PROJECT_ID}/alx-portfolio-image-to-pdf/alx-portfolio-image-to-pdf"

options:
  logging: CLOUD_LOGGING_ONLY
